language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
#  - cp CNAME docs/.vuepress/dist
branches:
  only:
    - master    # 构建的分支 发布到 master 分支 个人主页必须这样配置
# https://vuepress.vuejs.org/guide/deploy.html#github-pages
# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master