version: '3'

services:

  blog:
#    build: .
    image: node:15
    restart: always
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
#      - ./blog:/home/blog/blog:rw
      - ./:/home/blog/:rw
    working_dir: /home/blog
    command:
      - /bin/sh
      - -c
      - |
        yarn install
        yarn docs:dev